from agents.common import wrap_prompt

def build_prompt(ctx_text: str, agent_tag: str = "") -> str:
    core = """
			You are Agent-1 (global summary). Based on detections, output three lists:
			1) stable: base_class that appears in all samples with the same unique count.
			2) always_present: base_class that appears in all samples but with varying counts.
			3) sometimes_present: base_class that appears only in some samples.

			Counting rule:
			- num is an instance index, not a count; count = max num for that base_class in the image.

			Output format: only FACT_UPDATE and RULE_LINES blocks. No extra text.

			FACT_UPDATE:
			{
			"stable": [...],
			"always_present": [...],
			"sometimes_present": [...]
			}

			RULE_LINES (object array; agent must use agent_tag):
			- stable -> "each sample must have N <base_class>" (N is the true count)
			- always_present -> "each sample must contain <base_class>"
			- sometimes -> do NOT output rules in this stage; only write to FACT_UPDATE.
			  (sometimes rules will be generated by Agent-1-Counts.)
			If no rules, output [].

			Example:
			RULE_LINES:
			[
			{"rule_line":"each sample must have 2 tables","agent":"<agent_tag>"},
			{"rule_line":"each sample must contain boxes","agent":"<agent_tag>"}
			]
			"""
    return wrap_prompt(core, ctx_text, agent_tag=agent_tag)


def build_prompt_counts(ctx_text: str, agent_tag: str = "") -> str:
    core = """
			You are Agent-1-Counts (per-image statistics). Input includes labels per image and the sometimes_present list.
			Tasks (per image):
			1) counts_sometimes_by_image: for each image_id, list the count of each sometimes_present base_class.
			- count = max num for that base_class in the image.
			- if the base_class does not appear in the image, count must be 0 and still included.
			2) subtype_counts_by_image: for base_class that has subtypes, list the count of each subtype per image.
			- count = max num for that subtype in the image.
			- if a subtype does not appear in the image, it can be omitted.
			Output only FACT_UPDATE and RULE_LINES. No extra text.

			FACT_UPDATE:
			{
			"counts_sometimes_by_image": {},
			"subtype_counts_by_image": {}
			}
			RULE_LINES must be [].
			"""
    return wrap_prompt(core, ctx_text, agent_tag=agent_tag)
